<a href="https://colab.research.google.com/github/AndrewPolyak/PyTorch-Self-Learning/blob/main/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Andrew Polyak PyTorch Self-Learning Exercise

This represents my original attempt at completing the exercises provided by Daniel Bourke here:

https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

# ✓

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(size=(7, 7))
rand_tensor, rand_tensor.shape

# ✓

(tensor([[0.8154, 0.8364, 0.4353, 0.7357, 0.7915, 0.1207, 0.1728],
         [0.6274, 0.4644, 0.7242, 0.8789, 0.9883, 0.5785, 0.8702],
         [0.9808, 0.6144, 0.9755, 0.9404, 0.8576, 0.4125, 0.8855],
         [0.6393, 0.3463, 0.8516, 0.8007, 0.6811, 0.7539, 0.4217],
         [0.9302, 0.3855, 0.2821, 0.3520, 0.7775, 0.5457, 0.2378],
         [0.8291, 0.7761, 0.7966, 0.8627, 0.8325, 0.2366, 0.0806],
         [0.6085, 0.6041, 0.5837, 0.3738, 0.7741, 0.6039, 0.0314]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
rand_tensor2 = torch.rand(size=(1, 7))

# Perform matrix multiplication
product_tensor = torch.matmul(rand_tensor, rand_tensor2.T)
product_tensor, product_tensor.shape

# ✓

(tensor([[2.1920],
         [2.7321],
         [3.2821],
         [2.3587],
         [2.0523],
         [2.4227],
         [1.9773]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [29]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(size=(7, 7))
tensor2 = torch.rand(size=(1, 7))

# Matrix multiply tensors
product = torch.matmul(tensor1, tensor2.T)
product, product.shape

# ✓

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [30]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

# ✓


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [36]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)

print(f"Device: {device}")
tensor_A, tensor_B

# ✓

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [41]:
# Perform matmul on tensor_A and tensor_B
product = torch.matmul(tensor_A, tensor_B.T)
product, product.shape

# ✓

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [46]:
# Find max
print(f"Max Value: {torch.max(product)}")

# Find min
print(f"Min Value: {torch.min(product)}")

# ✓

Max Value: 0.5617256760597229
Min Value: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [47]:
# Find arg max
print(f"Max's Index: {torch.argmax(product)}")

# Find arg min
print(f"Min's Index: {torch.argmin(product)}")

# ✓

Max's Index: 3
Min's Index: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [53]:
# Set seed
torch.manual_seed(7)

# Create random tensor
my_tensor1 = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
my_tensor2 = my_tensor1.squeeze()

# Print out tensors and their shapes
print(my_tensor1, my_tensor1.shape)
print(my_tensor2, my_tensor2.shape)

# ✓

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
