<a href="https://colab.research.google.com/github/AndrewPolyak/PyTorch-Self-Learning/blob/main/exercises/Practice_Assignment_0_Tensors_and_Basic_Operations_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# 1. Creating a 1D Tensor
# Create a 1D tensor with 5 elements of type float32.

tensor = torch.rand(size=(5,), dtype=torch.float32)
tensor

tensor([0.5757, 0.4420, 0.2356, 0.7583, 0.6304])

In [ ]:
#2 Creating a 2D Tensor with Zeros
# Create a 2D tensor with shape (3, 4) filled with zeros.

tensor = torch.zeros(size=(3, 4))
tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# 3. Creating a 3D Tensor with Random Numbers
# Create a 3D tensor with shape (2, 3, 4) filled with random numbers.

tensor = torch.rand(size=(2, 3, 4))
tensor

tensor([[[0.4217, 0.7602, 0.0469, 0.7621],
         [0.2996, 0.3763, 0.9328, 0.6005],
         [0.3275, 0.4644, 0.0703, 0.8996]],

        [[0.2928, 0.2022, 0.0279, 0.4789],
         [0.7019, 0.7651, 0.3719, 0.8273],
         [0.5477, 0.3429, 0.6233, 0.6656]]])

In [ ]:
# 4. Tensor Properties
# Given a tensor a = torch.tensor([1, 2, 3]), what is its shape and data type?

a = torch.tensor([1, 2, 3])
print(a.shape, a.dtype)

# It's shape is [3]. It's datatype is int64

torch.Size([3]) torch.int64


In [ ]:
# 5. Element-wise Addition
# Perform element-wise addition of two tensors:
# a = torch.tensor([1, 2, 3]) and b = torch.tensor([4, 5, 6]).

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

print(torch.add(a, b))

tensor([5, 7, 9])


In [ ]:
# 6. Matrix Multiplication
# Perform matrix multiplication of two tensors:
# a = torch.tensor([[1, 2], [3, 4]]) and b = torch.tensor([[5, 6], [7, 8]]).

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print(torch.mm(a, b))

tensor([[19, 22],
        [43, 50]])


In [ ]:
# 7 Transposing a Tensor
# Transpose a tensor a = torch.tensor([[1, 2, 3], [4, 5, 6]]) and explain the resulting shape.

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)

a = a.T
print("\n", a)

# Explanation: The first row turns into the first column. The second row turns into the second column. Shape change from (2, 3) to (3 ,2)

tensor([[1, 2, 3],
        [4, 5, 6]])

 tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
# 8 Reshaping a Tensor
# Reshape a tensor a = torch.tensor([1, 2, 3, 4, 5, 6]) into a 2D tensor with shape (2, 3).

a = torch.tensor([1, 2, 3, 4, 5, 6])
a = torch.reshape(a, (2, 3))
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# 9 Indexing into a Tensor
# Index into a tensor a = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) to get the element at row 1, column 2.

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print (a[1][2])

tensor(6)


In [ ]:
# 10 Changing Data Type
# Change the data type of a tensor a = torch.tensor([1, 2, 3], dtype=torch.int32) to float32.

a = torch.tensor([1, 2, 3], dtype=torch.int32)
print(a.dtype)
a = a.type(torch.float32)
print(a.dtype)

torch.int32
torch.float32


In [ ]:
# 11 Broadcasting in Element-wise Multiplication
# Perform element-wise multiplication of a 1D tensor a = torch.tensor([1, 2, 3]) and a 2D tensor b = torch.tensor([[4, 5, 6], [7, 8, 9]]). Explain how broadcasting works in this case.

a = torch.tensor([1, 2, 3])
b = torch.tensor([[4, 5, 6],
                  [7, 8, 9]])

print(a.shape)
print(b.shape)
print(a * b)

# The broadcasting works since the tensor trailing shapes of 3 both match. The second trailing shapes are 2 and... none in a (fewer dimensions), meaning a 1 is prepended. This means they can multiply, since it would be like multiplying (1, 3) * (2, 3)

torch.Size([3])
torch.Size([2, 3])
tensor([[ 4, 10, 18],
        [ 7, 16, 27]])


In [ ]:
# 12 Incompatible Shapes for Matrix Multiplication
# Create two tensors with incompatible shapes for matrix multiplication and explain why they cannot be multiplied.

tensor1 = torch.rand(1, 2)
tensor2 = torch.rand(3, 4)
print (torch.mm(tensor1, tensor2))

# The "inner" dimensions between the two are not equal, meaning MM cannot be applied

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x2 and 3x4)

In [ ]:
# 13 Sum of Tensor Elements
# Calculate the sum of all elements in a tensor a = torch.tensor([[1, 2, 3], [4, 5, 6]]).

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
a.sum()

tensor(21)

In [ ]:
# 14 Finding the Maximum Value
# Find the maximum value in a tensor a = torch.tensor([1, 2, 3, 4, 5]).

a = torch.tensor([1, 2, 3, 4, 5])
a.max()

tensor(5)